# ATP TENNIS
link(https://www.kaggle.com/datasets/dissfya/atp-tennis-2000-2023daily-pull)

1. TOP 5: Jugadores que m√°s han ganado torneos y condiciones por jugador
2. Paises del mundo donde se han realizado torneos y su evoluci√≥n

# LIBRERIAS

In [320]:
import seaborn as sns
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# DATASET

In [321]:
df = pd.read_csv('../DATA/raw/atp_tennis.csv',sep=',') #dataset tennis
country = pd.read_csv('../DATA/raw/countries.csv') #dataset Country
city = pd.read_csv('../DATA/raw/cities.csv') #dataset Country
capitals = pd.read_csv('../DATA/raw/GlobalWeatherRepository.csv') #dataset capitals

In [322]:
city = city[['country_code','name']]
city

       country_code                 name
0                AF            AshkƒÅsham
1                AF             Fayzabad
2                AF                 Jurm
3                AF              Khand≈´d
4                AF            RƒÅghistƒÅn
...             ...                  ...
147395           ZW             Redcliff
147396           ZW             Shangani
147397           ZW             Shurugwi
147398           ZW    Shurugwi District
147399           ZW  Zvishavane District

[147400 rows x 2 columns]

In [325]:
capitals = capitals[['location_name', 'country']]
capitals.drop_duplicates(inplace= True)

In [326]:
capitals[capitals['location_name'] == 'Rome']

   location_name country
83          Rome   Italy

In [327]:
city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147400 entries, 0 to 147399
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   country_code  147352 non-null  object
 1   name          147400 non-null  object
dtypes: object(2)
memory usage: 2.2+ MB

In [328]:
city.dropna(inplace = True)

In [329]:
country.head(2)

,id,name,iso3,iso2,phone_code,capital,currency,currency_symbol,tld,native,region,subregion,timezones,latitude,longitude,emoji,emojiU
0,1,Afghanistan,AFG,AF,93,Kabul,AFN,ÿã,.af,ÿßŸÅÿ∫ÿßŸÜÿ≥ÿ™ÿßŸÜ,Asia,Southern Asia,"[{zoneName:'Asia\/Kabul',gmtOffset:16200,gmtOf...",33.000000,65.0,üá¶üá´,U+1F1E6 U+1F1EB
1,2,Aland Islands,ALA,AX,+358-18,Mariehamn,EUR,‚Ç¨,.ax,√Öland,Europe,Northern Europe,"[{zoneName:'Europe\/Mariehamn',gmtOffset:7200,...",60.116667,19.9,üá¶üáΩ,U+1F1E6 U+1F1FD

In [330]:
#capital = country[['iso2', 'capital']]
#capital.drop_duplicates(inplace = True)
#capital.rename (columns = {'capital': 'name', 'iso2': 'country_code'}, inplace= True)

In [331]:
'''
city = pd.concat([capital, city], join = 'inner')
city.drop_duplicates(inplace = True)
city.dropna(inplace = True)
city.info()

'''

"\ncity = pd.concat([capital, city], join = 'inner')\ncity.drop_duplicates(inplace = True)\ncity.dropna(inplace = True)\ncity.info()\n\n"

In [332]:
country = country[['iso2','name']]
country.dropna(inplace = True)
country.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 0 to 249
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   iso2    249 non-null    object
 1   name    249 non-null    object
dtypes: object(2)
memory usage: 5.8+ KB

In [333]:
df_city_country = pd.merge(country, city, left_on = 'iso2', right_on = 'country_code' , how = 'inner')
df_city_country = df_city_country[['name_y','name_x']]
df_city_country.rename(columns = {'name_y' : 'city', 'name_x': 'country'}, inplace = True)
df_city_country.head(10)

                        city      country
0                  AshkƒÅsham  Afghanistan
1                   Fayzabad  Afghanistan
2                       Jurm  Afghanistan
3                    Khand≈´d  Afghanistan
4                  RƒÅghistƒÅn  Afghanistan
5                     WƒÅkhƒÅn  Afghanistan
6                   Ghormach  Afghanistan
7                 Qala i Naw  Afghanistan
8                    BaghlƒÅn  Afghanistan
9  ·∏®uk≈´matƒ´ Dahanah-ye Gh≈çrƒ´  Afghanistan

In [334]:
capitals.rename(columns = {'location_name': 'city'}, inplace = True)

In [335]:
df_city_country = pd.concat([capitals, df_city_country], join = 'inner')

In [336]:
df_city_country.drop_duplicates(inplace = True)

In [337]:
dict_city_country = dict(zip(df_city_country[ 'city'], df_city_country['country'])) #diccionario con las ciudades y los paises

# ANALISIS

## VARIABLES

### FECHA | Date

In [338]:
df['Year'] = df['Date'].apply(lambda x: x.split('-')[0]).astype(int)
df['Month'] = df['Date'].apply(lambda x: x.split('-')[1]).astype(int)
df['Day'] = df['Date'].apply(lambda x: x.split('-')[2]).astype(int)

### JUGADORES | Player_1 | Player_2

In [339]:
lista = [df['Player_1'].unique()][0].tolist()
lista.extend([df['Player_1'].unique()][0].tolist())
lista_jugadores = set(lista)
lista = list(lista_jugadores)
lista

['Celikbilek A.',
 'Bogomolov Jr.A.',
 'Erler A.',
 'Casanova H.',
 'Elseneer G.',
 'Onoda M.',
 'Ramirez-Hidalgo R.',
 'Young D.',
 'Hui J.',
 'Roux L.',
 'Fitz S.',
 'Zverev M.',
 'Ferreira Silva F.',
 'Popyrin A.',
 'Raonic M.',
 'Ivanisevic G.',
 'Koellerer D. ',
 'Escobar G.',
 'Stoppini A.',
 'Eriksson M.',
 'Fratangelo B.',
 'Purcell M.',
 'Lama G.',
 'Ogorodov O.',
 'Sorensen L.',
 'Emmrich M.',
 'Forejtek J.',
 'Gremelmayr D.',
 'Tabilo A.',
 'Jones A.',
 'Marcan D.',
 'Nishikori K.',
 'Betov S.',
 'Kwon S.W.',
 'Robredo T. ',
 'Kim A.',
 'Hartfield D.',
 'Ferreiro F.',
 'di Mauro A.',
 'Choinski J.',
 'Stoliarov A.',
 'Moraru G.',
 'Simoni A.',
 'Abel M.',
 'Bjorkman J.',
 ' Hajek J.',
 'Goransson T.',
 'Berasategui A.',
 'Udomchoke D.',
 'Caruana L.',
 'Lopez San Martin A.',
 'Kern R.',
 'Schnur B.',
 'Clezar G.',
 'Stoltenberg J.',
 'Rosol L.',
 'Parada F.',
 'Kosakowski D.',
 'Yevseyev D.',
 'Chaen T.',
 'Whittington A.',
 'Millman J.',
 'Safin M.',
 'Lehecka J.',
 'Medjedovic H.',
 'Bautista R.',
 'Jeanpierre J.',
 'Ljubicic I.',
 'Kohlschreiber P.',
 'Behrend T.',
 'Haase R.',
 'Suzuki T.',
 'Pless K.',
 'Mathieu P.H.',
 'Klahn B.',
 'Marrero D.',
 'Murray A. ',
 'Del Potro J.',
 'Ito Y.',
 'Vovk S.',
 'Peric T.',
 'Pavic A.',
 'Sanchez D.',
 'Jaziri M.',
 'Norrie C.',
 'Tabara M.',
 'Johansson J.',
 'Patience O.',
 'Mergea F.',
 'Zeballos H. ',
 'Svrcina D.',
 'Mitchell B.',
 'Rublev A.',
 'Riba P.',
 'Elias G.',
 'Van De Zandschulp B.',
 'Patriarca D.',
 'Tsitsipas S. ',
 'Popp A.',
 'Przysiezny M.',
 'Rosset M.',
 'Watanuki Y.',
 'Aldi F.',
 'Moreno De Alboran N.',
 'Delbonis F.',
 'Zemlja G.',
 'Huta Galung J.',
 'Wu T.L.',
 'Meligeni Alves F.',
 'Smethurst D.',
 'Behr N.',
 'Matkowski M.',
 'Larsson M.',
 'Gabashvili T.',
 'Charpentier M.',
 'Barrere G.',
 'Pfeiffer K.',
 'Sachko V.',
 'Kyrgios N.',
 'Trungelliti M.',
 'Groth S.',
 'Rios M.',
 'Shane R.',
 'Arthurs W.',
 'Nielsen F.',
 'Kimmich M.',
 'Clemens T.',
 'Kralert P.',
 'Damm M.',
 'Garcia-Sintes J.',
 'Kukushkin M.',
 'Martineau M.',
 'Iwabuchi S.',
 'Millot V.',
 'De Schepper K.',
 'Lisnard J.',
 'Mcclune M.',
 'Roca Batalla O.',
 'Giannessi A.',
 'Junaid R.',
 'Mu T.',
 'Zverev A. ',
 'Wessels P.',
 'Polmans M.',
 'Eleskovic E.',
 'Krajicek R.',
 'Sijsling I.',
 'Mecir M.',
 'Nunez E.',
 'Borg L.',
 'Balleret B.',
 'Berdych T.',
 'Iwami T.',
 'Valkusz M.',
 'Mukund S.',
 'Meligeni Rodrigues F',
 'Paul T.',
 'Milojevic N.',
 'Boruszewski J.',
 'Hernych J. ',
 'Lammer M. ',
 'Martelli M.',
 'Carlsen K.',
 'Viloca J.A.',
 'Costa F.',
 'Biryukov M.',
 'Cowan B.',
 'Peralta J.',
 'Mpetshi G.',
 'Stark J.',
 'Olivo R.',
 'Sakamoto P.',
 'Zeng S.X.',
 'Machado R.',
 'Aragone JC',
 'Marin J.A',
 'Fischer M.',
 'Safiullin R.',
 'Snobel P.',
 'Nalbandian D.',
 'Odesnik W.',
 'Wolf J.J.',
 'Lu Y.',
 'Waske A.',
 'Brands D.',
 'Borvanov R.',
 'Boeker M.',
 'Matsukevitch D.',
 'Cipolla F.',
 'Gray A.',
 'Uchida K.',
 'Korteling S.',
 'Al Ghareeb M.',
 'Clayton A.',
 'Hadad A.',
 'Andreozzi G.',
 'Blanch U.',
 'Mina G.',
 'Friberg K.',
 'Lajovic D.',
 'Radic M.',
 'Sarstrand M.',
 'Puentes G.',
 'Zapata Miralles B.',
 'Gong M.X.',
 'Gooding J.',
 'Blake J.',
 'De Bakker T.',
 'Scherrer J.',
 'Janvier M.',
 'Gakhov I.',
 'Sanchez De Luna J.',
 'Sock J.',
 'El Amrani R.',
 'Tipsarevic J.',
 'Holmgren A.',
 'Marozsan F.',
 'Enqvist T.',
 'Auger-Aliassime F.',
 'Ledovskikh M.',
 'Flanagan I.',
 'Moya C.',
 'Fyrstenberg M.',
 'Kutsenko V.',
 'Cazaux A.',
 'Nam H.W.',
 'Serrano O.',
 'Ruud C.',
 'De Jong J.',
 'Spadea V.',
 'Korda S.',
 'Seyboth Wild T.',
 'Davydenko N. ',
 'Clarke J.',
 'Linzer M.',
 'Santillan A.',
 'Kempes E.',
 'Kilderry P.',
 'Borges N.',
 'Rodriguez M.',
 'Terachi T.',
 'Capalik K.',
 'Hernandez O.',
 'Cobolli F.',
 'Nakashima B.',
 'Alonso J.',
 'Bourgeois L.',
 'Agostinelli B.',
 'Broady L.',
 'Bolelli S.',
 'Deen Heshaam A.',
 'Oswald P.',
 'Hemmes F.',
 'Cakl T.',
 'Lejnieks K.',
 'Querrey S.',
 'Agaev E.',
 'Kavcic B.',
 'McClune M.',
 'Zayid M. S.',
 'Pellegrino A.',
 'Veronelli D.',
 'Kubot L.',
 'Kutrovsky D.',
 'Yu X.Y.',
 'Shelbayh A.',
 'Vavassori A.',
 'Decoud S.',
 "Dell'Acqua M.",
 'Erlich J.',
 'Al-Alawi S.K.',
 'MacLagan M.',
 'Echagaray B.',
 'Daniel T.',
 'Giner J.',
 'Dzumhur D.',
 'Geerts M.',
 'Klein L.',
 'Bryan B.',
 'Salamanca C.',
 'Jonsson F.',
 'Polansky P.',
 'Hemery C.',
 'Marach O.',
 'Lacko L.',
 'Benneteau A.',
 'Machac T.',
 'Aguilar J.',
 'Pucinelli de Almeida M.',
 'Ketola T.',
 'Flygt K.',
 'Fish A.',
 'Medvedev A.',
 'Marchenko I.',
 'Ebden M.',
 'Navarro S.',
 'Meligeni F.',
 'Mayer L. ',
 'Youzhny M. ',
 'Otte O.',
 'Torpegaard M.',
 'Gimelstob J.',
 'Fasching A.',
 'Chardy J. ',
 'de Voest R.',
 'Herbert P.H',
 'Prinosil D.',
 'Jenkins S.',
 'Karanusic R.',
 'Slanar M.',
 'Wu Y.',
 'Munoz De La Nava D.',
 'Mankad H.',
 'Oudsema S.',
 'Rochus C. ',
 'Menendez-Maceiras A.',
 'De Voest R.',
 'Anderson K.',
 'Novak D.',
 'Tenconi T.',
 'Tepavac M.',
 'Monfils G. ',
 'Warburg S.',
 'Pioline C.',
 'Gojo B.',
 'Johnson S.',
 'Knippschild J.',
 'Nishioka Y.',
 'Dabul B.',
 'Goffin D.',
 'Van Lottum J.',
 'Nedovyesov A.',
 'Robredo T.',
 'Valent R.',
 'Nadal R.',
 'Traykov I.',
 'Wang Y.',
 'Moroni G.M.',
 'Albot R.',
 'Satral J.',
 'Hirigoyen I.',
 'Diez S.',
 'Wang J.',
 'Monfils G.',
 'Chidekh C.',
 'Kunitsyn I.',
 'Hijikata R.',
 'Nardi L.',
 'Skugor F.',
 'Ilhan M.',
 'Davydenko N.',
 'Schuettler P.',
 'Lu Y.H.',
 'Bemelmans R.',
 'Burquier G.',
 'Garin C.',
 'Krstin P.',
 'Tarallo S.',
 'Willis M.',
 'Galan D.E.',
 'Faurel J.C.',
 'Lopez-Moron A.',
 'Cilic M.',
 'Coppejans K.',
 'Kolar Z.',
 'Cilic M. ',
 'Shapovalov D.',
 'Nadal R. ',
 'Levine I.',
 'Sousa J.',
 'Weiner G.',
 'Dustov F.',
 'Stricker D.',
 'Salva B.',
 'Guardiola T.',
 'Arnaldi M.',
 'Vik R.',
 'Dupuis A.',
 'Matosevic M.',
 'Pescariu D.',
 'Bruguera S.',
 'Paes L.',
 'Vacek J.',
 'Guzman J.P.',
 'Mutis O.',
 'Gonzalez P.',
 'Hocevar R.',
 'Costa A.',
 'Harsanyi P.',
 'Alves M.',
 'Hellstrom M.',
 'Dutra Silva R.',
 'De Greef A.',
 'Bautista Agut R.',
 'Vardhan V.',
 'Raoux G.',
 'Agenor R.',
 'Struff J.L.',
 'Baker J.',
 'Ivanov-Smolensky K.',
 'Velotti A.',
 'Stepanek R. ',
 'Vacherot V.',
 'Sell M.',
 'Bagnis F.',
 'Holt B.',
 'Fromberg R.',
 'Carretero R.',
 'Bellucci T.',
 'Coria F.',
 'Verdasco M.',
 'Cui J.',
 'Dancevic F.',
 'Mcdonald M.',
 'Oncins J.',
 'Caruso S.',
 'Kecmanovic M.',
 'Ziadi M.',
 'Wassen R.',
 'Baez S.',
 'Chekov P.',
 'Troicki V. ',
 'Skatov T.',
 'Moser F.',
 'Jung J.',
 'Kwiatkowski T.S.',
 'Kovalik J.',
 'Chela J.I.',
 'Lee D.H.',
 'Garcia-Lopez G. ',
 'Rocha H.',
 'Arvidsson I.',
 'Ancic I.',
 'Almagro N. ',
 'Reister J.',
 'Van D. Merwe I.',
 'Meffert D.',
 'Medvedev D.',
 'Miranda I.',
 'Gigounon G.',
 'Goellner M.K.',
 'Gomez E.',
 'Souza J.',
 'Zekic M.',
 'Maden Y.',
 'Godwin N.',
 'Pella G.',
 'Matias N.',
 'Mello R.',
 'Walton A.',
 'Ymer M.',
 'Zeppieri G.',
 'Becker B.',
 'Kopriva V.',
 'Agamenone F.',
 'Bowles C.',
 'Galovic V.',
 'Hernych J.',
 'Rosenholm P.',
 'Misolic F.',
 'Wawrinka S.',
 'Mertl J.',
 'Hoang A.',
 'Kratochvil M.',
 'Goodall J.',
 'Jiang S.',
 "O'Connell C.",
 'Catarina L.',
 'Melo D.',
 'Mazarakis V.',
 'Cook L.',
 'Lajola D.',
 'Marray J.',
 'Eaton C.',
 'Silva D.',
 'Benneteau J.',
 'Guinard M.',
 'Koubek S.',
 'Tomic B.',
 'Gensse A.',
 'Kucera V.',
 'Ungur A.',
 'Caldwell D.',
 'Chappell N.',
 'Childs L.',
 'Sanguinetti D.',
 'Massu N.',
 'Lopez-Jaen M.A.',
 'Klaasen R.',
 'Struvay E.',
 'Yang T.H.',
 'King E.',
 'Villanueva G.',
 'Lapentti G.',
 'Tipsarevic J. ',
 'Yani M.',
 'Kondo H.',
 'Safwat M.',
 'Huesler M.A.',
 'Courier J.',
 'Smith J.P.',
 'Zverev A.',
 'Hajek J.',
 'Ferrer D.',
 'Pescosolido S.',
 'Brizzi A.',
 'Samper-Montana J.',
 'Isner J.',
 'Mirnyi M.',
 'Liukko V.',
 'Kim K.',
 'Taino E.',
 'Mager G.',
 'Reneberg R.',
 'Lazov A.',
 'Berlocq C.',
 'Demoliner M.',
 'Murray A.',
 'Djere L.',
 'Guccione C.',
 'Malisse X.',
 'Johansson T.',
 'Tarango J.',
 'Aragone J.',
 'Kutac R.',
 'Munar J.',
 'Dosedel S.',
 'Wang Y.T.',
 'Knowle J.',
 'Verdasco F.',
 'Niland C.',
 'Mensik J.',
 'Etcheverry T.',
 'Minar J.',
 'Trinker B.',
 'Lee H.T.',
 'Varillas J.P.',
 'Krajicek A.',
 'Thiem D.',
 'Jun W.',
 'Williams R.',
 'Pouille L.',
 'Ward A.',
 'Tong M.',
 'Sanchez M.',
 'Bachelot J.F',
 'Muster T.',
 'Soderling R.',
 'Karatsev A.',
 'Griekspoor T.',
 'Statham J.',
 'Ram A.',
 'Bogaerts R.',
 'El Aarej M.',
 'Giraldo S.',
 'Andreev I.',
 'Ancic M.',
 'Sarkissian A.',
 'Varlet J.',
 'Brasington J.',
 'Bloomfield R.',
 'Masur D.',
 'Cressy M.',
 'Reyes-Varela M.A.',
 'Saulnier C.',
 'Cerundolo J.M.',
 'Djokovic N. ',
 'Srichaphan P.',
 'van Scheppingen D.',
 'Alvarez E.',
 'Morrison J.',
 'Vajda I.',
 'Kudryavtsev A.',
 'Mannarino A.',
 'Bonzi B.',
 'Marrai M.',
 'Lammer M.',
 'Robert S.',
 'Vemic D.',
 'Chen T.',
 'Willems R.',
 'Coutelot N.',
 'Cecchinato M.',
 'Seppi A. ',
 'Chaki R.',
 'Sweeny D.',
 'Okun N.',
 'Hank T.',
 'Lopes H.',
 'Diallo G.',
 'Tu L.',
 'Golding O.',
 'Zeballos H.',
 'Henman T.',
 'Tseng C. H.',
 'Amritraj P.',
 'Ruusuvuori E.',
 'Ficovich J.P.',
 'Rochus O. ',
 'Serra F. ',
 'Monaco J.',
 'Philippoussis M.',
 'Pavel A.',
 'Harris A.',
 'Norman M.',
 'Nava E.',
 'Lorenzi P.',
 'Pospisil J.',
 'Sabau R.',
 'Ugo Carabelli C.',
 'Gicquel M.',
 'Mackin A.',
 'Majchrzak K.',
 'Alcaide G.',
 'Craca M.',
 'Donati M.',
 'Zhukayev B.',
 'Kuznetsov An.',
 'Grenier H.',
 'Riffice S.',
 'Piros Z.',
 'Vilella Martinez M.',
 'Friedl L.',
 'de Chaunac S.',
 'Tsonga J.W.',
 'Haider-Maurer A.',
 'Passaro F.',
 'Awadhy O.',
 'Vukic A.',
 'Rastogi K.',
 'Gaudi I.',
 'Thomann N.',
 'Sousa T.',
 'Del Potro J.M.',
 'Baldi F.',
 'Armando H.',
 'Mektic N.',
 'Kokkinakis T.',
 'Sun P.',
 'Vatutin A.',
 'Ouahab L.',
 'Kudla D.',
 'Hewitt L.',
 'Shyla Y.',
 'Zhang Zh.',
 'Youzhny M.',
 'Tobon M.',
 'Gaio F.',
 'Napolitano S.',
 'van Lottum J.',
 'Blake T.',
 'Chardy J.',
 'Furlan R.',
 'Lisnard J.R.',
 'Spottl M.',
 'Timfjord N.',
 'Kuhn N.',
 'Nadal-Parera R.',
 'Lajal M.',
 'Bublik A.',
 'Allegro Y.',
 'Ryderstedt M.',
 'Gutierrez-Ferrol S.',
 'Santopadre V.',
 'Vlasov D.',
 'Puerta M.',
 'Prashanth V.',
 'Ojeda Lara R.',
 'Basic M.',
 'Couto E.',
 'Korolev E. ',
 'Saville L.',
 'Roitman S.',
 'Sonego L.',
 'Venus M.',
 'Tahiri M.',
 'Halys Q.',
 'Riba-Madrid P.',
 'Matsui T.',
 'Massa E.',
 'Michon A.',
 'Riedi L.',
 'Gumy H.',
 'Gerasimov E.',
 'Loffhagen G.',
 'Hurkacz H.',
 'Barrientos N.',
 'Jouan R.',
 'Troicki V.',
 'Carreno-Busta P.',
 'Delgado R.',
 'Muller G.',
 'Eitzinger R.',
 'Granollers G.',
 'Baghdatis M.',
 'Ahouda A.',
 'Takeuchi K.',
 'Sandbichler A.',
 'Teixeira M.',
 'Boutter J.',
 'Ondruska M.',
 'Levy H.',
 'Perez D.',
 'Hilton M.',
 'Klein T.',
 'Mota B.',
 'Ratiwatana S.',
 'Recouderc L.',
 'Karlovic I.',
 'Landaluce M.',
 'Kuzmanov D.',
 'Pecotic M.',
 'Zopp J.',
 'Karlovskiy E.',
 'Baluda V.',
 'Rola B.',
 'Gallardo M.',
 'Simon G. ',
 'Fucsovics M.',
 'Crivoi V.',
 'Berrer M.',
 'Krutykh O.',
 'Topic J.',
 'Calatrava A.',
 'Trujillo G.',
 'Furness E.',
 'Chvojka E.',
 'Savolt A.',
 'Levinsky J.',
 'Van Der Merwe I.',
 'Singh N.',
 'Singh S.',
 'Quinn E.',
 'Simonsson F.',
 'di Pasquale A.',
 'Gonzalez S.',
 'Harris L.',
 'Knittel B.',
 'Rodrigues M.',
 'Bogomolov Jr. A.',
 'Ferrero J.',
 'Istomin D.',
 'De Minaur A.',
 'Lopez-Perez E.',
 'Atmane T.',
 'Sekulic P.',
 'Gregorc L.',
 'Caratti C.',
 'Gallardo Valles M.',
 'Cervantes I.',
 'Peniston R.',
 'Taberner C.',
 'Rufin G.',
 'Qureshi A.',
 'Larose S.',
 'Fleming C.',
 'Dolgopolov A.',
 'Schoorel T.',
 'Kiefer N.',
 'Smyczek T.',
 'Kuznetsov Al.',
 'Dodig I.',
 'Bergs Z.',
 'Montanes A. ',
 'Rincon D.',
 'Chiudinelli M.',
 'Maestrelli F.',
 'Van der Dium A.',
 'Canas G.',
 'Hipfl M.',
 'Luncanu P.A.',
 'Sherwood D.',
 'Molcan A.',
 'Sa A.',
 'Rubin N.',
 'Humphries S.',
 'Parmar A.',
 'Calleri A.',
 'Ionita V.',
 'Rehnquist B.',
 'Qureshi A.U.H.',
 'Trifu G.',
 'Belal C.',
 'Rybakov A.',
 'Bellier A.',
 'Ilkel C.',
 'Tirante T.A.',
 'Hrbaty D.',
 'Ivashka I.',
 'Evans B.',
 'Pavic M.',
 'Black W.',
 'Cermak F.',
 'Naso G.',
 'Ellwood B.',
 'Cox D.',
 'Ofner S.',
 'Granollers Pujol G.',
 'Poerschke L.',
 'Koellerer D.',
 'Mayer F.',
 'Khalfan S.',
 'Fish M.',
 'Tveit E.',
 'Petzschner P.',
 'Moriya H.',
 'Yim R.',
 'Ljubicic I. ',
 'Zhu B.Q.',
 'Bozic I.',
 'Gaudenzi A.',
 'Klec I.',
 'Economidis K.',
 'Del Potro J. M.',
 'Bossel A.',
 'Agassi A.',
 'Dasnieres de Veigy J.',
 'Dent T.',
 'Sela D.',
 'Filippini M.',
 'Golovanov D.',
 'Paire B.',
 'Mochizuki S.',
 'Li Z.',
 'Querry S.',
 'Malcor O.',
 'Vahaly B.',
 'Burrieza O.',
 'Manta L.',
 'Barton M.',
 'Vanni L.',
 'Clement A.',
 'Bangoura S.',
 'Sluiter R.',
 'Sweeting R.',
 'Ulihrach B.',
 'Granollers M. ',
 'Couacaud E.',
 'Koepfer D.',
 'Lopez Villasenor G.',
 'Fraile G.',
 'Golubev A.',
 'Darderi L.',
 'Behrmann M.',
 'Evans D.',
 'Bastl G.',
 'Gojowczyk P.',
 'Gasquet R. ',
 'Simmonds P.',
 'Sampras P.',
 'Te R.',
 'Stebe C.M.',
 'Nielsen M.',
 'Dutra Da Silva R.',
 'Cervenak P.',
 'Peya A.',
 'Peliwo F.',
 'Lu H.',
 'Olivetti A.',
 'Mansouri S.',
 'Todero N.',
 'Nieminen J.',
 'Rinderknech A.',
 'Rodriguez Taverna S.',
 'Galvani S.',
 'Schwartzman D.',
 'Rodionov J.',
 'Travaglia S.',
 'Diaz J.',
 'Montcourt M.',
 'Marin J.A.',
 'Haider-Mauer A.',
 'Ginepri R.',
 'Shvec A.',
 'Rachidi Y.',
 'Jubb P.',
 'Draper S.',
 'Fognini F.',
 'Labadze I.',
 'Kravchuk K.',
 'Isner J. ',
 'Tsitsipas S.',
 'Chung H.',
 'Ram R.',
 'Thron A.',
 'Serra F.',
 'Brooksby J.',
 'Gil F.',
 'Del Bonis F.',
 'Bracciali D.',
 'Donskoy E.',
 'Bopanna R.',
 'Kamke T.',
 'Marti J.',
 'Do M.Q.',
 'Almagro N.',
 'Balcells J.',
 'Luczak P.',
 'Van der Merwe I.',
 'Ferrero J.C.',
 'Rettenmaier T.',
 'Ilie A.',
 'Aranguren J.M.',
 'Junqueira D.',
 'Bohli S.',
 'Berrettini M.',
 'Shimabukuro S.',
 'Van Assche L.',
 'Chadaj A.',
 'Schukin Y.',
 'Llodra M.',
 'Kendrick R.',
 'Kypson P.',
 'Lamasine T.',
 'Seppi A.',
 'Ittogi T.',
 'Jelenic P.',
 'Luxa P.',
 'Gross O.',
 'Luczak P. ',
 'Robredo R.',
 'Bower J.',
 'Dimitrov G.',
 'Djokovic M.',
 'Mantilla F.',
 'Barrios M.',
 'Eysseric J.',
 'Mejia N.',
 'Tuksar S.',
 'Mathieu P.H. ',
 'Roger-Vasselin E.',
 'Nestor D.',
 'Ortegren J.',
 'Bolelli S. ',
 'Ouanna J.',
 'Basilashvili N.',
 'Brown D.',
 'Voinea A.',
 'Tyurnev E.',
 'Lapentti N.',
 'Munoz-De La Nava D.',
 'Tiafoe F.',
 'Arazi H.',
 'Humbert U.',
 'Andersen J.F.',
 'Vagnozzi S.',
 'Bedene A.',
 'Dewulf F.',
 'Bozoljac I.',
 'Janowicz J.',
 'Kohlmann M.',
 'Britton D.',
 'Hernandez-Fernandez J.',
 'Medvedev D. ',
 'Palmer J.',
 'Yoon Y.',
 'Bolt A.',
 'Korolev E.',
 'Lenz J.',
 'Munoz de La Nava D.',
 'Buchanan C.',
 'Froberg J.',
 'Martin T.',
 'Ito T.',
 'Copil M.',
 'Bhambri Y.',
 'Fancutt T.',
 'Dreekmann H.',
 'Santoro F.',
 'Vacek D.',
 'Durasovic V.',
 'Bester P.',
 'Setkic A.',
 'Cuadrado C.',
 'Dupre T.',
 'Bohane A.',
 'Schalken S.',
 'Tieleman L.',
 'Musetti L.',
 'Draper J.',
 'Kroslak J.',
 'Sitak A.',
 'Moraing M.',
 'Ramanathan R.',
 'Harrison C.',
 'Lestienne C.',
 'Mott B.',
 'Klein B.',
 'Fidirko N.',
 'Kovacevic A.',
 'Motomura G.',
 'Woodforde M.',
 'Bogomolov A.',
 'Navarro-Pastor I.',
 'Cuevas P.',
 'Ignatik U.',
 'Tseng C.H.',
 'Klizan M.',
 'Landsberg J.',
 'Miedler L.',
 ...]

### RONDA | Round

In [340]:
df['Round'].unique()
lista_rondas = [7,6,3,2,1,4,5,10]
dic_round =dict(zip(df['Round'].unique(), lista_rondas))
dic_round

{'1st Round': 7,
 '2nd Round': 6,
 'Quarterfinals': 3,
 'Semifinals': 2,
 'The Final': 1,
 '3rd Round': 4,
 '4th Round': 5,
 'Round Robin': 10}

### TORNEO |Tournament |Series | Court | Surface

In [341]:
dict_torneo = dict()

In [342]:
def def_country(x):
    bandera = True
    for country in df_city_country['country'].unique():
            if country in x:
                bandera = False
                dict_torneo[x] = country  
    if bandera:
        for city in dict_city_country.keys():
            if city in x: 
                dict_torneo[x] = dict_city_country[city]
            else: 
                dict_torneo[x] = None

In [343]:
for torneo in df['Tournament'].unique():
    def_country(torneo)

In [344]:
df['Country'] = df['Tournament'].apply(lambda x: dict_torneo[x])

In [345]:
df

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,...,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,Year,Month,Day,Country
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,...,77,-1,-1,-1.00,-1.00,6-4 6-2,2000,1,3,Australia
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,...,5,-1,-1,-1.00,-1.00,3-6 3-6,2000,1,3,Australia
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,...,655,-1,-1,-1.00,-1.00,6-7 7-5 6-3,2000,1,3,Australia
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,...,65,-1,-1,-1.00,-1.00,1-6 4-6,2000,1,3,Australia
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,Fromberg R.,...,198,-1,-1,-1.00,-1.00,7-6 5-7 6-4,2000,1,3,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61663,ASB Classic,2024-01-10,ATP250,Outdoor,Hard,Quarterfinals,3,Muller A.,Daniel T.,Daniel T.,...,74,711,739,1.91,1.91,4-6 7-6 3-6,2024,1,10,None
61664,ASB Classic,2024-01-11,ATP250,Outdoor,Hard,Quarterfinals,3,Shelton B.,Carballes Baena R.,Shelton B.,...,67,2145,796,1.17,5.00,6-4 6-3,2024,1,11,None
61665,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Shelton B.,Daniel T.,Daniel T.,...,74,2145,739,1.22,4.33,5-7 6-7,2024,1,12,None
61666,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Tabilo A.,Fils A.,Tabilo A.,...,35,707,1208,4.00,1.25,6-2 7-5,2024,1,12,None
61667,ASB Classic,2024-01-13,ATP250,Outdoor,Hard,The Final,3,Daniel T.,Tabilo A.,Tabilo A.,...,82,739,707,1.73,2.10,2-6 5-7,2024,1,13,None

In [346]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61668 entries, 0 to 61667
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  61668 non-null  object
 1   Date        61668 non-null  object
 2   Series      61668 non-null  object
 3   Court       61668 non-null  object
 4   Surface     61668 non-null  object
 5   Round       61668 non-null  object
 6   Best of     61668 non-null  int64
 7   Player_1    61668 non-null  object
 8   Player_2    61668 non-null  object
 9   Winner      61668 non-null  object
 10  Rank_1      61668 non-null  int64
 11  Rank_2      61668 non-null  int64
 12  Pts_1       61668 non-null  int64
 13  Pts_2       61668 non-null  int64
 14  Odd_1       61668 non-null  float64
 15  Odd_2       61668 non-null  float64
 16  Score       61668 non-null  object
 17  Year        61668 non-null  int32
 18  Month       61668 non-null  int32
 19  Day         61668 non-null  int32
 20  Country     7981 non-null   object
dtypes: float64(2), int32(3), int64(5), object(11)
memory usage: 9.2+ MB

In [347]:
df['Tournament'][df['Country'].isnull()].unique()

array(['Gold Flake Open', 'Heineken Open', 'Sydney International',
       'Dubai Open', 'Marseille Open', 'Sybase Open', 'Kroger St. Jude',
       'ABN AMRO World Tennis Tournament', 'AXA Cup', 'Mexican Open',
       'Copenhagen Open', 'Citrix Tennis Championships', 'Chevrolet Cup',
       'Franklin Templeton Tennis Classic', 'Ericsson Open',
       'Galleryfurniture.com Tennis Challenge', 'Grand Prix Hassan II',
       'Estoril Open', 'Monte Carlo Masters', 'Open Seat Godo',
       'Mallorca Open', 'BMW Open', 'U.S. Clay Court Championships',
       'Rome TMS', 'Hamburg TMS', 'Internationaler Raiffeisen Grand Prix',
       'French Open', 'Gerry Weber Open', 'Stella Artois',
       'Nottingham Open', 'Heineken Trophy', 'Wimbledon', 'Swedish Open',
       'Gstaad Open', 'Hall of Fame Championships', 'Dutch Open',
       'Mercedes Cup', 'Generali Open', 'Mercedes-Benz Cup',
       'Toronto TMS', 'Cincinnati TMS', 'RCA Championships',
       'Legg Mason Classic', 'The Hamlet Cup', 'US Open',
       "President's Cup", 'Campionati Internazionali Di Sicilia',
       'Salem Open', 'CA Tennis Trophy', 'Heineken Open Shanghai',
       'adidas Open', 'Swiss Indoors', 'Kremlin Cup', 'Stuttgart TMS',
       'Grand Prix de Lyon', 'St. Petersburg Open', 'BNP Paribas',
       'Samsung Open', 'Stockholm Open', 'Masters Cup',
       'AAPT Championships', 'TATA Open', 'adidas International',
       'Milan Indoors', 'Bellsouth Open', 'Copa AT&T', 'Abierto Mexicano',
       'Dubai Championships', 'Verizon Tennis Challenge',
       "U.S. Men's Clay Court Championships", 'Idea Prokom Open',
       'Montreal TMS', 'Hamlet Cup', 'Gelsor Open', 'Brasil Open',
       'Pacific Life Open', 'NASDAQ-100 Open', 'Queens Club',
       'Ordina Open', 'Energis Open', 'TD Waterhouse Cup',
       'Madrid Masters', 'Breil ATP', 'Open 13', 'Siebel Open',
       'International Championships', 'CAM Open Comunidad Valenciana',
       'Telecom Italia Masters Roma', 'Allianz Suisse Open',
       'Priority Telecom Dutch Open',
       'Western & Southern Financial Group Masters', 'Open de Moselle',
       'Indesit ATP Milano Indoor ', 'ATP Buenos Aires 2004',
       'Next Generation Hardcourts', 'Medibank International',
       'Internazionali di Lombardia', 'ATP Buenos Aires 2005', 'SAP Open',
       'Regions Morgan Keegan Championships',
       "Dubai Duty Free Men's Open", 'Channel Open',
       'Open de Tenis Comunidad Valenciana', 'Rogers Cup',
       'Pilot Pen Tennis', 'BA-CA Tennis Trophy',
       'Davidoff Swiss Indoors', 'Next Generation Adelaide International',
       'Chennai Open', 'Movistar Open', 'PBZ Zagreb Indoors',
       'Copa Telmex', 'Dubai Tennis Championships',
       "Campionati Internazional d'Italia",
       'Hypo Group Tennis International', 'Red Letter Days Open',
       'Synsam Swedish Open', 'Countrywide Classic', 'Rogers Masters',
       'Kingfisher Airlines Tennis Open', 'Sony Ericsson Open',
       "Internazionali BNL d'Italia", 'The Nottingham Open',
       'Catella Swedish Open', 'Open Sabadell Atl√°ntico 2008',
       'Orange Prokom Open', 'Slazenger Open', 'Brisbane International',
       'SA Tennis Open', 'BNP Paribas Open', 'Open Banco Sabadell',
       'Mutua Madrile√±a Madrid Open', 'AEGON Championships',
       'AEGON International', 'International German Open',
       'LA Tennis Open', 'Shanghai Masters', 'Valencia Open 500',
       'BNP Paribas Masters', 'Open de Nice C√¥te d‚ÄôAzur', 'Unicef Open',
       'SkiStar Swedish Open', 'Atlanta Tennis Championships',
       'German Open Tennis Championships', 'Farmers Classic',
       'Copa Claro', 'Bet-At-Home Cup',
       'Winston-Salem Open at Wake Forest University', 'Erste Bank Open',
       'Apia International', 'VTR Open', 'BRD Nastase Tiriac Trophy',
       'Mutua Madrid Open', 'BB&T Atlanta Open',
       'Cr√©dit Agricole Suisse Open Gstaad', 'Citi Open',
       'U.S. National Indoor Tennis Championships', 'Power Horse Cup',
       'Topshelf Open', 'Delray Beach Open', 'Rio Open',
       'Dusseldorf Open', 'bet-at-home Open', 'Shenzhen Open',
       'Memphis Open', 'Millenium Estoril Open', 'Istanbul Open',
       'Geneva Open', 'AEGON Open', 'Suisse Open Gstaad', 'ASB Classic',
       'Garanti Koza Sofia Open', 'German Tennis Championships',
       'Abierto Mexicano Mifel', 'Chengdu Open', 'European Open',
       'Open Banco Sabadell ', 'Gazprom Hungarian Open', 'Lyon Open',
       'Ricoh Open', 'Antalya Open', 'Tata Open', 'New York Open',
       'Millennium Estoril Open', 'Eastbourne International',
       'Maharashtra Open', 'Cordoba Open', 'Sofia Open', 'Hungarian Open',
       'Rosmalen Grass Court Championships', 'Halle Open',
       "Queen's Club Championships", 'Zhuhai Open',
       'Adelaide International', 'bett1HULKS Indoors',
       'Forte Village Sardegna Open', 'bett1HULKS Championship',
       'Astana Open', 'Great Ocean Road Open', 'Murray River Open',
       'Miami Open', 'Sardegna Open', 'AnyTech365 Andalucia Open',
       'Barcelona Open', 'Belgrade Open', 'Emilia-Romagna Open',
       'Viking International', 'Mallorca Championships', 'Nordea Open',
       'Mifel Open', 'Canadian Open', 'San Diego Open', 'Vienna Open',
       'Adelaide International 1', 'Melbourne Summer Set',
       'Adelaide International 2', 'Sydney Tennis Classic', 'Dallas Open',
       'Atlanta Open', 'Los Cabos Open', 'Korea Open', 'Tel Aviv Open',
       'Firenze Open', 'Gijon Open', 'Napoli Cup', 'Srpska Open',
       'Stuttgart Open', 'Zhuhai Championships', 'Nordic Open',
       'Hong Kong Tennis Open'], dtype=object)

In [348]:
torneos_special = ['Kroger St. Jude', 
                   'ABN AMRO World Tennis Tournament', 
                   'AXA Cup',
                   'Chevrolet Cup', 
                   'Monte Carlo Masters', #
                   'Stella Artois',
                   'Heineken Trophy', 
                   'The Hamlet Cup', #
                   "President's Cup",
                   'CA Tennis Trophy', 
                   'Swiss Indoors', #
                   'Kremlin Cup', 
                   'BNP Paribas',
                   'Masters Cup', 
                   'adidas International', 
                   'Copa AT&T',
                   'Abierto Mexicano', #
                   'Verizon Tennis Challenge', 
                   'Montreal TMS',#
                   'Hamlet Cup', #
                   'Breil ATP',
                   'Western & Southern Financial Group Masters',
                   'Medibank International', 
                   'BA-CA Tennis Trophy', 
                   'Copa Telmex',#
                   'Hypo Group Tennis International', 
                   'Countrywide Classic',
                   "Internazionali BNL d'Italia", #
                   'AEGON International',
                   'BNP Paribas Masters', 
                   'Farmers Classic', 
                   'Copa Claro',#
                   'ASB Classic', 
                   'Abierto Mexicano Mifel', #
                   'bett1HULKS Indoors',
                   'Viking International', 
                   'Napoli Cup']

In [349]:
country_torneo_especial = ['United States', 
                           'Nehterlands', 
                           'United Kingdom',
                           'Chile', 
                           'Monaco', #
                           'United Kingdom',
                           'Nehterlands', 
                           'United States', #
                           "Kazakhstan",
                           'Austria', 
                           'Sweden', #
                           'Russia', 
                           'Spain',
                           'Masters Cup', 
                           'Australia', 
                           'Argentina',
                           'Mexico', #
                           'United States', 
                           'Canada',#
                           'United States', #
                           'Brazil',
                           'United States',
                           'Australia',
                           'Austria', 
                           'Mexico',#
                           'Austria', 
                           'United States',
                           "Italy", #
                           'United Kingdom',
                           'India', 
                           'United States', 
                           'Argentina',#
                           'New Zealand', 
                           'Mexico', #
                           'Germany',
                           'United Kingdom', 
                           'Italy']

In [350]:
dict_torneo_country = dict(zip(torneos_special, country_torneo_especial))

In [351]:
dict_torneo_country

{'Kroger St. Jude': 'United States',
 'ABN AMRO World Tennis Tournament': 'Nehterlands',
 'AXA Cup': 'United Kingdom',
 'Chevrolet Cup': 'Chile',
 'Monte Carlo Masters': 'Monaco',
 'Stella Artois': 'United Kingdom',
 'Heineken Trophy': 'Nehterlands',
 'The Hamlet Cup': 'United States',
 "President's Cup": 'Kazakhstan',
 'CA Tennis Trophy': 'Austria',
 'Swiss Indoors': 'Sweden',
 'Kremlin Cup': 'Russia',
 'BNP Paribas': 'Spain',
 'Masters Cup': 'Masters Cup',
 'adidas International': 'Australia',
 'Copa AT&T': 'Argentina',
 'Abierto Mexicano': 'Mexico',
 'Verizon Tennis Challenge': 'United States',
 'Montreal TMS': 'Canada',
 'Hamlet Cup': 'United States',
 'Breil ATP': 'Brazil',
 'Western & Southern Financial Group Masters': 'United States',
 'Medibank International': 'Australia',
 'BA-CA Tennis Trophy': 'Austria',
 'Copa Telmex': 'Mexico',
 'Hypo Group Tennis International': 'Austria',
 'Countrywide Classic': 'United States',
 "Internazionali BNL d'Italia": 'Italy',
 'AEGON International': 'United Kingdom',
 'BNP Paribas Masters': 'India',
 'Farmers Classic': 'United States',
 'Copa Claro': 'Argentina',
 'ASB Classic': 'New Zealand',
 'Abierto Mexicano Mifel': 'Mexico',
 'bett1HULKS Indoors': 'Germany',
 'Viking International': 'United Kingdom',
 'Napoli Cup': 'Italy'}

In [352]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61668 entries, 0 to 61667
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  61668 non-null  object
 1   Date        61668 non-null  object
 2   Series      61668 non-null  object
 3   Court       61668 non-null  object
 4   Surface     61668 non-null  object
 5   Round       61668 non-null  object
 6   Best of     61668 non-null  int64
 7   Player_1    61668 non-null  object
 8   Player_2    61668 non-null  object
 9   Winner      61668 non-null  object
 10  Rank_1      61668 non-null  int64
 11  Rank_2      61668 non-null  int64
 12  Pts_1       61668 non-null  int64
 13  Pts_2       61668 non-null  int64
 14  Odd_1       61668 non-null  float64
 15  Odd_2       61668 non-null  float64
 16  Score       61668 non-null  object
 17  Year        61668 non-null  int32
 18  Month       61668 non-null  int32
 19  Day         61668 non-null  int32
 20  Country     7981 non-null   object
dtypes: float64(2), int32(3), int64(5), object(11)
memory usage: 9.2+ MB

In [353]:
for torneo in dict_torneo_country.keys():
    df['Country'][df['Tournament'] == torneo] = dict_torneo_country[torneo]

C:\Users\cmzga\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [354]:
len(dict_torneo_country.keys())

37

In [355]:
len(torneos_special )

37

In [356]:
for x in torneos_special:
    if not x in dict_torneo_country.keys():
        print(x)

In [357]:
df['Tournament'][df['Country'].isnull()].unique()

array(['Gold Flake Open', 'Heineken Open', 'Sydney International',
       'Dubai Open', 'Marseille Open', 'Sybase Open', 'Mexican Open',
       'Copenhagen Open', 'Citrix Tennis Championships',
       'Franklin Templeton Tennis Classic', 'Ericsson Open',
       'Galleryfurniture.com Tennis Challenge', 'Grand Prix Hassan II',
       'Estoril Open', 'Open Seat Godo', 'Mallorca Open', 'BMW Open',
       'U.S. Clay Court Championships', 'Rome TMS', 'Hamburg TMS',
       'Internationaler Raiffeisen Grand Prix', 'French Open',
       'Gerry Weber Open', 'Nottingham Open', 'Wimbledon', 'Swedish Open',
       'Gstaad Open', 'Hall of Fame Championships', 'Dutch Open',
       'Mercedes Cup', 'Generali Open', 'Mercedes-Benz Cup',
       'Toronto TMS', 'Cincinnati TMS', 'RCA Championships',
       'Legg Mason Classic', 'US Open',
       'Campionati Internazionali Di Sicilia', 'Salem Open',
       'Heineken Open Shanghai', 'adidas Open', 'Stuttgart TMS',
       'Grand Prix de Lyon', 'St. Petersburg Open', 'Samsung Open',
       'Stockholm Open', 'AAPT Championships', 'TATA Open',
       'Milan Indoors', 'Bellsouth Open', 'Dubai Championships',
       "U.S. Men's Clay Court Championships", 'Idea Prokom Open',
       'Gelsor Open', 'Brasil Open', 'Pacific Life Open',
       'NASDAQ-100 Open', 'Queens Club', 'Ordina Open', 'Energis Open',
       'TD Waterhouse Cup', 'Madrid Masters', 'Open 13', 'Siebel Open',
       'International Championships', 'CAM Open Comunidad Valenciana',
       'Telecom Italia Masters Roma', 'Allianz Suisse Open',
       'Priority Telecom Dutch Open', 'Open de Moselle',
       'Indesit ATP Milano Indoor ', 'ATP Buenos Aires 2004',
       'Next Generation Hardcourts', 'Internazionali di Lombardia',
       'ATP Buenos Aires 2005', 'SAP Open',
       'Regions Morgan Keegan Championships',
       "Dubai Duty Free Men's Open", 'Channel Open',
       'Open de Tenis Comunidad Valenciana', 'Rogers Cup',
       'Pilot Pen Tennis', 'Davidoff Swiss Indoors',
       'Next Generation Adelaide International', 'Chennai Open',
       'Movistar Open', 'PBZ Zagreb Indoors',
       'Dubai Tennis Championships', "Campionati Internazional d'Italia",
       'Red Letter Days Open', 'Synsam Swedish Open', 'Rogers Masters',
       'Kingfisher Airlines Tennis Open', 'Sony Ericsson Open',
       'The Nottingham Open', 'Catella Swedish Open',
       'Open Sabadell Atl√°ntico 2008', 'Orange Prokom Open',
       'Slazenger Open', 'Brisbane International', 'SA Tennis Open',
       'BNP Paribas Open', 'Open Banco Sabadell',
       'Mutua Madrile√±a Madrid Open', 'AEGON Championships',
       'International German Open', 'LA Tennis Open', 'Shanghai Masters',
       'Valencia Open 500', 'Open de Nice C√¥te d‚ÄôAzur', 'Unicef Open',
       'SkiStar Swedish Open', 'Atlanta Tennis Championships',
       'German Open Tennis Championships', 'Bet-At-Home Cup',
       'Winston-Salem Open at Wake Forest University', 'Erste Bank Open',
       'Apia International', 'VTR Open', 'BRD Nastase Tiriac Trophy',
       'Mutua Madrid Open', 'BB&T Atlanta Open',
       'Cr√©dit Agricole Suisse Open Gstaad', 'Citi Open',
       'U.S. National Indoor Tennis Championships', 'Power Horse Cup',
       'Topshelf Open', 'Delray Beach Open', 'Rio Open',
       'Dusseldorf Open', 'bet-at-home Open', 'Shenzhen Open',
       'Memphis Open', 'Millenium Estoril Open', 'Istanbul Open',
       'Geneva Open', 'AEGON Open', 'Suisse Open Gstaad',
       'Garanti Koza Sofia Open', 'German Tennis Championships',
       'Chengdu Open', 'European Open', 'Open Banco Sabadell ',
       'Gazprom Hungarian Open', 'Lyon Open', 'Ricoh Open',
       'Antalya Open', 'Tata Open', 'New York Open',
       'Millennium Estoril Open', 'Eastbourne International',
       'Maharashtra Open', 'Cordoba Open', 'Sofia Open', 'Hungarian Open',
       'Rosmalen Grass Court Championships', 'Halle Open',
       "Queen's Club Championships", 'Zhuhai Open',
       'Adelaide International', 'Forte Village Sardegna Open',
       'bett1HULKS Championship', 'Astana Open', 'Great Ocean Road Open',
       'Murray River Open', 'Miami Open', 'Sardegna Open',
       'AnyTech365 Andalucia Open', 'Barcelona Open', 'Belgrade Open',
       'Emilia-Romagna Open', 'Mallorca Championships', 'Nordea Open',
       'Mifel Open', 'Canadian Open', 'San Diego Open', 'Vienna Open',
       'Adelaide International 1', 'Melbourne Summer Set',
       'Adelaide International 2', 'Sydney Tennis Classic', 'Dallas Open',
       'Atlanta Open', 'Los Cabos Open', 'Korea Open', 'Tel Aviv Open',
       'Firenze Open', 'Gijon Open', 'Srpska Open', 'Stuttgart Open',
       'Zhuhai Championships', 'Nordic Open', 'Hong Kong Tennis Open'],
      dtype=object)